#!/usr/bin/env python3
import sys
import re
import numpy as np
import matplotlib.pyplot as plt

def parse_ping_file(filename):
    """
    Parses ping output generated by `ping -D -n -i 0.2 <host>`
    Line format: [1690000000.123456] 64 bytes from 1.2.3.4: icmp_seq=1 ttl=54 time=123.4 ms
    """
    pattern = re.compile(r'\[(\d+\.\d+)\]\s+.*icmp_seq=(\d+)\s+ttl=\d+\s+time=(\d+(?:\.\d+)?)\s*ms')
    
    timestamps = []
    seq_nums = []
    rtts = []
    
    with open(filename, 'r') as f:
        for line in f:
            match = pattern.search(line)
            if match:
                ts = float(match.group(1))
                seq = int(match.group(2))
                rtt = float(match.group(3))
                timestamps.append(ts)
                seq_nums.append(seq)
                rtts.append(rtt)
                
    if not seq_nums:
        print(f"Error: Could not parse any valid ping lines from {filename}")
        sys.exit(1)
        
    min_seq = min(seq_nums)
    max_seq = max(seq_nums)
    total_sent = max_seq - min_seq + 1
    total_recv = len(seq_nums)
    delivery_rate = total_recv / total_sent
    
    # Map received seq numbers to RTT and timestamp
    received_dict = {seq: rtt for seq, rtt in zip(seq_nums, rtts)}
    
    # Calculate streak statistics
    max_success_streak = 0
    curr_success_streak = 0
    max_loss_burst = 0
    curr_loss_burst = 0
    
    loss_vector = [] # 1 for received, 0 for lost
    
    for seq in range(min_seq, max_seq + 1):
        if seq in received_dict:
            curr_success_streak += 1
            max_success_streak = max(max_success_streak, curr_success_streak)
            
            if curr_loss_burst > 0:
                max_loss_burst = max(max_loss_burst, curr_loss_burst)
                curr_loss_burst = 0
            loss_vector.append(1)
        else:
            curr_loss_burst += 1
            max_loss_burst = max(max_loss_burst, curr_loss_burst)
            
            if curr_success_streak > 0:
                max_success_streak = max(max_success_streak, curr_success_streak)
                curr_success_streak = 0
            loss_vector.append(0)
            
    print("=" * 50)
    print(f"📊 ANALYSIS REPORT FOR: {filename}")
    print("=" * 50)
    print(f"Total packets sent: {total_sent}")
    print(f"Total packets received: {total_recv}")
    print(f"Overall Delivery Rate: {delivery_rate * 100:.2f}%")
    print(f"Packet Loss Rate: {(1 - delivery_rate) * 100:.2f}%")
    print(f"Longest Success Streak: {max_success_streak} packets")
    print(f"Longest Loss Burst: {max_loss_burst} packets")
    print(f"Min RTT: {min(rtts):.2f} ms")
    print(f"Max RTT: {max(rtts):.2f} ms")
    print(f"Mean RTT: {np.mean(rtts):.2f} ms")
    print(f"Median RTT: {np.median(rtts):.2f} ms")
    print("=" * 50)

    # --- Plotting Graphs ---
    plt.figure(figsize=(14, 10))

    # Plot 1: RTT vs Time
    plt.subplot(2, 2, 1)
    norm_ts = np.array(timestamps) - timestamps[0]
    plt.plot(norm_ts / 60.0, rtts, linewidth=0.5, color='blue', alpha=0.7)
    plt.title('1. RTT as a Function of Time')
    plt.xlabel('Time (minutes)')
    plt.ylabel('RTT (ms)')
    plt.grid(True)

    # Plot 2: Cumulative Distribution Function (CDF)
    plt.subplot(2, 2, 2)
    sorted_rtts = np.sort(rtts)
    cdf = np.arange(1, len(sorted_rtts) + 1) / len(sorted_rtts)
    plt.plot(sorted_rtts, cdf, color='green', linewidth=1.5)
    plt.title('2. Cumulative Distribution Function (CDF) of RTT')
    plt.xlabel('RTT (ms)')
    plt.ylabel('Cumulative Probability')
    plt.grid(True)

    # Plot 3: Scatter Plot of RTT(N) vs RTT(N+1)
    plt.subplot(2, 2, 3)
    rtts_n = []
    rtts_n1 = []
    for i in range(len(seq_nums) - 1):
        if seq_nums[i+1] == seq_nums[i] + 1:
            rtts_n.append(rtts[i])
            rtts_n1.append(rtts[i+1])
    plt.scatter(rtts_n, rtts_n1, alpha=0.3, s=5, color='purple')
    plt.title('3. Correlation: RTT(N) vs RTT(N+1)')
    plt.xlabel('RTT N (ms)')
    plt.ylabel('RTT N+1 (ms)')
    plt.grid(True)

    # Plot 4: Autocorrelation / Conditional Loss Probabilities
    plt.subplot(2, 2, 4)
    lags = list(range(-10, 11))
    prob_recv_given_recv = []
    loss_arr = np.array(loss_vector)
    for k in lags:
        if k == 0:
            prob_recv_given_recv.append(1.0)
            continue
        if k > 0:
            cond = loss_arr[:-k] == 1
            target = loss_arr[k:]
        else:
            cond = loss_arr[-k:] == 1
            target = loss_arr[:k]
        if np.sum(cond) > 0:
            prob = np.mean(target[cond] == 1)
        else:
            prob = 0.0
        prob_recv_given_recv.append(prob)

    plt.bar(lags, prob_recv_given_recv, color='orange', alpha=0.7)
    plt.axhline(y=delivery_rate, color='red', linestyle='--', label=f'Overall Delivery Rate ({delivery_rate*100:.1f}%)')
    plt.title('4. Conditional Delivery Rate P(Recv N+k | Recv N)')
    plt.xlabel('Lag k')
    plt.ylabel('Probability')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    output_png = filename.replace('.txt', '_analysis.png')
    plt.savefig(output_png, dpi=300)
    print(f"✅ Generated analysis figure: {output_png}")
    plt.show()

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python3 analyze_ping.py <ping_output_file.txt>")
        sys.exit(1)
    parse_ping_file(sys.argv[1])
